---
- name: grab os / distribution / version specific tasks
  include_tasks: "{{ item }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}/{{ ansible_distribution }}/{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}/{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
  loop: "{{ query('first_found', params, errors='ignore') }}"
